### ISSUE TITLE
Troubles getting authorised on Host from the Mvc application

### ISSUE THREAD

**Issue by Qonstrukt** [aspnetboilerplate/module-zero-core-template#361]
I'm using the Mvc template and run the application in Docker using multiple containers and an Nginx proxy. When doing API calls from the Mvc project to the Host, they all result in 401 Unauthorized exceptions, and I'm not sure how to debug this.

I'm using docker-compose with the Nginx proxy on a Mac to be able to run both applications from a single port and IP address using the following config:
```
version: '3.4'

services:
  proxy:
    image: [redacted]
    build:
      context: nginx
      dockerfile: Dockerfile
    depends_on:
      - mvc
      - api

  redis:
    image: redis

  mvc:
    image: [redacted]
    build:
      context: .
      dockerfile: src/[redacted].Web.Mvc/Dockerfile
    depends_on:
      - redis

  api:
    image: [redacted]
    build:
      context: .
      dockerfile: src/[redacted].Web.Host/Dockerfile
    depends_on:
      - redis
```
The Nginx proxy proxies everything to the Mvc application, except for the /api path. But I've tried connecting straight to the correct container by setting `appPath` in `_Layout.cshtml` to the container, and it's always Unauthorized as well.

I'm not sure where to start in how to debug, or what else I could try in setting this up. Has anyone else tried this setup and got it working?

In case anyone is wondering how I got this running so far with the Nginx proxy:
```
worker_processes 1;
 
events { worker_connections 1024; }

http {
    sendfile on;
 
    upstream docker-api {
        server api:80;
    }
 
    upstream docker-mvc {
        server mvc:80;
    }

    server {
        listen 80;
    
        server_name localhost;
        
        proxy_pass_header  Authorization;
        proxy_pass_header  Set-Cookie;
        proxy_pass_header  X-XSRF-TOKEN;
       
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host $server_name;
        proxy_set_header   X-Forwarded-Proto $scheme;
        
        location /signalr {
            proxy_pass         http://docker-mvc;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection "Upgrade";
        }

        location /api {
            proxy_pass         http://docker-api;
        }

        location /swagger {
            proxy_pass         http://docker-api;
        }

        location / {
            proxy_pass         http://docker-mvc;
        }
    }
}
```
